services:
  src:
    build: ./
    depends_on:
      - db
    volumes:
      - ./src:/src
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    #network_mode: "host"
    restart: always