services:
  src:
    build: ./
    depends_on:
      - db
    volumes:
      - ./src:/src
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DBNAME}
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: always